services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dagster-daemon:
    build: .
    command: dagster-daemon run -m repo.repository
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      DAGSTER_POSTGRES_HOST: ${DAGSTER_POSTGRES_HOST}
      DAGSTER_HOME: ${DAGSTER_HOME}
      INFLUXDB_HOST: ${INFLUXDB_HOST}
      INFLUXDB_PORT: ${INFLUXDB_PORT}
      INFLUXDB_DATABASE: ${INFLUXDB_DATABASE}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
      INFLUXDB_QUERY: ${INFLUXDB_QUERY}
      SPARK_PACKAGES: ${SPARK_PACKAGES}
      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET: ${R2_BUCKET}
      R2_PREFIX: ${R2_PREFIX}
      R2_REGION: ${R2_REGION}
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - postgres

  dagster-webserver:
    build: .
    command: dagster-webserver -h 0.0.0.0 -p 3000 -m repo.repository
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: ${DAGSTER_POSTGRES_USER}
      DAGSTER_POSTGRES_PASSWORD: ${DAGSTER_POSTGRES_PASSWORD}
      DAGSTER_POSTGRES_DB: ${DAGSTER_POSTGRES_DB}
      DAGSTER_POSTGRES_HOST: ${DAGSTER_POSTGRES_HOST}
      DAGSTER_HOME: ${DAGSTER_HOME}
      INFLUXDB_HOST: ${INFLUXDB_HOST}
      INFLUXDB_PORT: ${INFLUXDB_PORT}
      INFLUXDB_DATABASE: ${INFLUXDB_DATABASE}
      INFLUXDB_USERNAME: ${INFLUXDB_USERNAME}
      INFLUXDB_PASSWORD: ${INFLUXDB_PASSWORD}
      INFLUXDB_QUERY: ${INFLUXDB_QUERY}
      SPARK_PACKAGES: ${SPARK_PACKAGES}
      R2_ENDPOINT: ${R2_ENDPOINT}
      R2_ACCESS_KEY_ID: ${R2_ACCESS_KEY_ID}
      R2_SECRET_ACCESS_KEY: ${R2_SECRET_ACCESS_KEY}
      R2_BUCKET: ${R2_BUCKET}
      R2_PREFIX: ${R2_PREFIX}
      R2_REGION: ${R2_REGION}
    volumes:
      - dagster_home:/opt/dagster/dagster_home
    depends_on:
      - postgres

volumes:
  postgres_data:
  dagster_home:
