jobs:

  influx_to_r2:
    entrypoint: jobs/influx_to_r2.py
    spark:
      executor_instances: 2
      executor_memory: 2g
      driver_memory: 1g
      conf: {}
    params:
      - date
      - bucket

  cryptocompare_to_r2:
    entrypoint: jobs/cryptocompare_to_r2.py
    spark:
      executor_instances: 2
      executor_memory: 2g
      driver_memory: 1g
      conf: {}
    params: []

  daily_aggregation:
    entrypoint: jobs/daily_aggregation.py
    spark:
      executor_instances: 2
      executor_memory: 2g
      driver_memory: 1g
      conf: {}
    params:
      - date
